apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pod-example
spec:
  selector:
    matchLabels:
      app: basic-demo
  replicas: 1
  template: 
    metadata:
      labels:
        app: basic-demo
    spec:
     containers:
     - name: basic-demo
       image: marcgeorge/basic-app:v1
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: exploit-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: basic-demo
